[versions]
kotlin = "2.3.20"
serialization = "1.11.0"
compose-plugin = "1.10.0-alpha03"
kubriko = "0.0.8"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kubriko-engine = { module = "io.github.pandulapeter.kubriko:engine-desktop", version.ref = "kubriko" }
kubriko-plugin-keyboard-input = { module = "io.github.pandulapeter.kubriko:plugin-keyboard-input-desktop", version.ref = "kubriko" }
kubriko-plugin-sprites = { module = "io.github.pandulapeter.kubriko:plugin-sprites-desktop", version.ref = "kubriko" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
