package com.tankarena.tools.mapconv

import java.io.File

object LegacyPictureCatalogExtractor {
    private val worlds = listOf(
        "DESERT" to "pc0",
        "TEMPERATE" to "pc1",
        "CITY" to "pc2",
        "NIGHT" to "pc3",
    )

    fun generateKotlin(sourceFile: File, outputFile: File) {
        val source = sourceFile.readText()
        val catalogs = worlds.associate { (label, variable) ->
            label to parseNames(source = source, variable = variable)
        }

        outputFile.parentFile?.mkdirs()
        outputFile.writeText(renderKotlin(catalogs))
    }

    private fun parseNames(source: String, variable: String): List<String> {
        val marker = "$variable[]={"
        val start = source.indexOf(marker)
        require(start >= 0) { "Could not find $variable in pictures.c source." }
        val blockStart = start + marker.length
        val blockEnd = source.indexOf("};", blockStart)
        require(blockEnd > blockStart) { "Could not find end of $variable initializer." }
        val block = source.substring(blockStart, blockEnd)

        val entries = mutableListOf<String>()
        var depth = 0
        val current = StringBuilder()
        for (character in block) {
            if (character == '{') depth += 1
            if (depth > 0) current.append(character)
            if (character == '}') {
                depth -= 1
                if (depth == 0) {
                    val primaryName = PRIMARY_NAME_REGEX.find(current.toString())?.groupValues?.get(1)
                    if (primaryName == null) break
                    entries += primaryName
                    current.clear()
                }
            }
        }
        return entries
    }

    private fun renderKotlin(catalogs: Map<String, List<String>>): String {
        val builder = StringBuilder()
        builder.appendLine("package com.tankarena.content")
        builder.appendLine()
        builder.appendLine("// Generated by :tools-mapconv extract-pictures from src/data/pictures.c.")
        builder.appendLine("internal object GeneratedLegacyPictureCatalog {")
        catalogs.forEach { (label, names) ->
            val propertyName = label.lowercase() + "Names"
            builder.appendLine("    val $propertyName: List<String> = listOf(")
            names.forEach { name ->
                builder.append("        ")
                builder.append(name.asKotlinStringLiteral())
                builder.appendLine(",")
            }
            builder.appendLine("    )")
            builder.appendLine()
        }
        builder.appendLine("}")
        return builder.toString()
    }

    private fun String.asKotlinStringLiteral(): String {
        return buildString {
            append('"')
            this@asKotlinStringLiteral.forEach { character ->
                when (character) {
                    '\\' -> append("\\\\")
                    '"' -> append("\\\"")
                    else -> append(character)
                }
            }
            append('"')
        }
    }

    private val PRIMARY_NAME_REGEX = Regex("""\{\{\s*"([^"]+)"""")
}
